# vim:ft=ruby

Vagrant.configure('2') do |config|
  config.ssh.forward_agent = true
  config.vm.box = 'ubuntu-14.04'
  config.vm.box_url = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box'
  config.vm.host_name = 'frogpoint'
  config.vm.network 'forwarded_port', guest: 22, host: 2200
  config.vm.network 'forwarded_port', guest: 80, host: 8000
  config.vm.synced_folder '../frogpoint', '/frogpoint'

  config.vm.provider 'virtualbox' do |v|
    v.name = 'frogpoint'
    v.customize ['modifyvm', :id, '--memory', 512]
    v.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
  end
end
